export const itemdata = [
    { item_image: "/assets/items/Bonda.jpg" },
    { item_image: "/assets/items/Dosa.jpg" },
    { item_image: "/assets/items/Idli.jpg" },
    { item_image: "/assets/items/Juice.jpg" },
    { item_image: "/assets/items/Pancake.jpg" },
    { item_image: "/assets/items/Paratha.jpg" },
    { item_image: "/assets/items/Poha.jpg" },
    { item_image: "/assets/items/Poori.jpg" },
    { item_image: "/assets/items/Vada.jpg" },
    { item_image: "/assets/items/Biryani.avif" },
    { item_image: "/assets/items/Cakes.avif" },
    { item_image: "/assets/items/Pastry.avif" },
    { item_image: "/assets/items/Burger.avif" },
    { item_image: "/assets/items/Ice-cream.avif" },
    { item_image: "/assets/items/North Indian.avif" },
    { item_image: "/assets/items/South Indian.avif" },
    { item_image: "/assets/items/Momos.avif" },
    { item_image: "/assets/items/Kebabs.avif" },
    { item_image: "/assets/items/Pasta.avif" },
    { item_image: "/assets/items/Chinese.avif" },
    { item_image: "/assets/items/Shawarma.avif" },
    { item_image: "/assets/items/Shakes.avif" },
    { item_image: "/assets/items/Rolls.avif" },
    { item_image: "/assets/items/Pure Veg.avif" },
];
